steps:
  - id: terraform
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args:
      - "-c"
      - |
        chmod +x terraform/terraforminit.sh
        ./terraform/terraforminit.sh "${_APPLY}"
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _APPLY: "N"  
