github_owner                 = "archieflynn" // My GitHub Username
repo_name                    = "BritEdge" // My forked repo name
project_id                   = "britedge2" // My GCP Project ID
region                       = "europe-west2" //  region
build_sa_name                  = "cloudbuild@britedge2.iam.gserviceaccount.com" // Replace with your Project ID
github_app_installation_id   = "82921739" 
github_oauth_token_secret    = "projects/britedge2/secrets/britedge-eu1-github-oauthtoken/versions/1"
dockertag                    = "v0.0.1" // first version tag
cloudsql_password_secret     = "projects/britedge2/secrets/CloudSQL-user/versions/1"
